//! Garden integration.
//!
//! `garden grow` already clones missing trees, applies per-tree git
//! configuration, is idempotent, converges configuration changes, and never
//! touches a working tree. `aw` therefore owns only the translation from
//! `workspace.toml` into garden's tree vocabulary.
//!
//! The generated file is included by a hand-editable `garden.yaml` rather than
//! being merged into it, so custom commands never need reconciling.

use crate::manifest::{Identity, Manifest};
use anyhow::{Context, Result};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Oldest garden known to support `garden.includes` and per-tree `gitconfig`.
pub const MIN_VERSION: (u32, u32) = (2, 6);

pub const GENERATED_DIR: &str = ".aw";
pub const GENERATED_FILE: &str = ".aw/trees.yaml";
pub const CONFIG_FILE: &str = "garden.yaml";

/// Render the manifest's repositories as a garden configuration fragment.
///
/// Deterministic: identical manifests produce byte-identical output, which is
/// what makes `aw bootstrap` a no-op on the second run.
pub fn render_trees(manifest: &Manifest) -> String {
    let mut out = String::from(
        "# Generated by `aw` from workspace.toml. Do not edit — regenerated wholesale.\n\ntrees:\n",
    );

    if manifest.repos.is_empty() {
        out.push_str("  {}\n");
        return out;
    }

    for repo in &manifest.repos {
        let _ = writeln!(out, "  {}:", yaml_key(&repo.tree_name()));
        let _ = writeln!(out, "    path: {}", yaml_str(&repo.path));
        let _ = writeln!(out, "    url: {}", yaml_str(&repo.url));
        if let Some(branch) = &repo.branch {
            let _ = writeln!(out, "    branch: {}", yaml_str(branch));
        }
        let gitconfig = identity_pairs(manifest.identity.as_ref());
        if !gitconfig.is_empty() {
            out.push_str("    gitconfig:\n");
            for (key, value) in gitconfig {
                let _ = writeln!(out, "      {key}: {}", yaml_str(&value));
            }
        }
    }
    out
}

/// Git configuration keys implied by the manifest's identity block.
///
/// Shared by tree generation and by the workspace repository itself, so the
/// workspace never drifts from the repositories it manages.
pub fn identity_pairs(identity: Option<&Identity>) -> Vec<(&'static str, String)> {
    let Some(identity) = identity else {
        return Vec::new();
    };
    let mut pairs = Vec::new();
    if let Some(name) = &identity.name {
        pairs.push(("user.name", name.clone()));
    }
    if let Some(email) = &identity.email {
        pairs.push(("user.email", email.clone()));
    }
    if let Some(key) = &identity.signingkey {
        pairs.push(("user.signingkey", key.clone()));
    }
    if let Some(sign) = identity.gpgsign {
        pairs.push(("commit.gpgsign", sign.to_string()));
    }
    pairs
}

/// Write the generated fragment, returning whether the file changed.
pub fn write_trees(root: &Path, manifest: &Manifest) -> Result<bool> {
    let path = root.join(GENERATED_FILE);
    let rendered = render_trees(manifest);
    if std::fs::read_to_string(&path).is_ok_and(|existing| existing == rendered) {
        return Ok(false);
    }
    std::fs::create_dir_all(root.join(GENERATED_DIR))
        .with_context(|| format!("creating {}", root.join(GENERATED_DIR).display()))?;
    std::fs::write(&path, rendered).with_context(|| format!("writing {}", path.display()))?;
    Ok(true)
}

/// Grow every tree in the manifest. Missing trees are cloned; present trees
/// have their git configuration converged. Working trees are never touched.
pub fn grow(root: &Path, manifest: &Manifest) -> Result<()> {
    if manifest.repos.is_empty() {
        return Ok(());
    }
    let mut cmd = Command::new("garden");
    cmd.arg("-C").arg(root).arg("grow");
    for repo in &manifest.repos {
        cmd.arg(repo.tree_name());
    }
    let status = cmd
        .status()
        .context("running `garden grow` — is garden on PATH?")?;
    anyhow::ensure!(status.success(), "`garden grow` failed with {status}");
    Ok(())
}

/// Installed garden version as `(major, minor)`.
pub fn version() -> Result<(u32, u32)> {
    let out = Command::new("garden")
        .arg("--version")
        .output()
        .context("running `garden --version` — is garden on PATH?")?;
    anyhow::ensure!(out.status.success(), "`garden --version` failed");
    let text = String::from_utf8_lossy(&out.stdout);
    parse_version(&text).with_context(|| format!("parsing garden version from {text:?}"))
}

fn parse_version(text: &str) -> Option<(u32, u32)> {
    let digits = text
        .split_whitespace()
        .find(|w| w.starts_with(|c: char| c.is_ascii_digit()))?;
    let mut parts = digits.split('.');
    Some((parts.next()?.parse().ok()?, parts.next()?.parse().ok()?))
}

/// Absolute checkout path of a manifest entry, resolved against the workspace.
pub fn checkout_path(root: &Path, relative: &str) -> PathBuf {
    root.join(relative)
}

/// YAML mapping keys are constrained to tree names, which are already
/// alphanumeric-with-dashes, but quote defensively so a hand-edited manifest
/// cannot produce a malformed fragment.
fn yaml_key(value: &str) -> String {
    yaml_str(value)
}

/// Single-quoted YAML scalar. Single quotes are the only character needing an
/// escape inside them, doubled per the YAML specification.
fn yaml_str(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest(toml: &str) -> Manifest {
        toml::from_str(toml).expect("fixture parses")
    }

    #[test]
    fn renders_optional_branch_only_when_present() {
        let rendered = render_trees(&manifest(
            r#"
            [workspace]
            name = "w"
            [[repo]]
            path = "alpha"
            url = "git@example.com:alpha.git"
            branch = "main"
            [[repo]]
            path = "beta"
            url = "git@example.com:beta.git"
            "#,
        ));
        assert!(rendered.contains("branch: 'main'"), "{rendered}");
        assert_eq!(rendered.matches("branch:").count(), 1, "{rendered}");
    }

    #[test]
    fn renders_identity_as_per_tree_gitconfig() {
        let rendered = render_trees(&manifest(
            r#"
            [workspace]
            name = "w"
            [identity]
            name = "Ada"
            email = "ada@example.com"
            gpgsign = true
            [[repo]]
            path = "alpha"
            url = "git@example.com:alpha.git"
            "#,
        ));
        assert!(rendered.contains("user.name: 'Ada'"), "{rendered}");
        assert!(rendered.contains("commit.gpgsign: 'true'"), "{rendered}");
    }

    #[test]
    fn escapes_single_quotes_in_scalars() {
        assert_eq!(yaml_str("O'Brien"), "'O''Brien'");
    }

    #[test]
    fn flattens_nested_paths_into_tree_names() {
        let manifest = manifest(
            r#"
            [workspace]
            name = "w"
            [[repo]]
            path = "vendor/alpha"
            url = "u"
            [[repo]]
            path = "vendor/beta.worktree"
            url = "u"
            "#,
        );
        assert_eq!(manifest.repos[0].tree_name(), "vendor-alpha");
        assert_eq!(manifest.repos[1].tree_name(), "vendor-beta-worktree");
    }

    #[test]
    fn empty_manifest_renders_valid_empty_mapping() {
        let rendered = render_trees(&manifest("[workspace]\nname = \"w\"\n"));
        assert!(rendered.ends_with("trees:\n  {}\n"), "{rendered}");
    }

    #[test]
    fn parses_garden_version_banner() {
        assert_eq!(parse_version("garden 2.6.1\n"), Some((2, 6)));
    }
}
